# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Dev Branch CI

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
      - 'feature/**'
      - 'feat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.25.0
          run_install: true
      - name: Linter
        run: pnpm lint
      - name: Build
        run: pnpm build
